apiVersion: v1
kind: Service
metadata:
  name: http-test-service
  labels:
    app: http-test-service
spec:
  selector:
    app: http-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-test-ingress
spec:
  rules:
    - host: http-test.com # 这里要更改成你自己的域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: http-test-service
                port:
                  number: 80

